/*CREATE DATABASE KUTUPHANE_ODEVI
USE KUTUPHANE_ODEVI*/
/*CREATE TABLE UYELER(
UYE_NO INT PRIMARY KEY,
UYE_AD NVARCHAR(50),
UYE_SOYAD NVARCHAR(50),
CINSIYET NVARCHAR(5),
TELEFON NVARCHAR(50),
E_POSTA VARCHAR(100),
)

CREATE TABLE ADRESLER(
ADRES_NO INT PRIMARY KEY,
SEHIR NVARCHAR(50),
MAHALLE NVARCHAR(50),
CADDE NVARCHAR(50),
BINA_NO INT ,
POSTA_KODU INT,
ULKE NVARCHAR(50))

CREATE TABLE KUTUPHANE(
KUTUPHAHE_NO INT PRIMARY KEY,
ADRES_NO INT,
TELEFON_NO INT,
E_POSTA NVARCHAR(50)
CONSTRAINT ADRES_NO_PK FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER([ADRES_NO]))

CREATE TABLE KATEGORI(
KATEGORI_NO INT PRIMARY KEY,
KATEGORI_AD NVARCHAR(50))

CREATE TABLE YAZARLAR(
YAZAR_NO INT PRIMARY KEY,
YAZAR_ADI NVARCHAR(50),
YAZAR_SOYADI NVARCHAR(50))

CREATE TABLE KITAPLAR(
KITAP_NO INT PRIMARY KEY,
KITAP_ADI NVARCHAR(50),
ISBN NVARCHAR(50),
SAYFA_SAYISI INT,
YAZAR_NO INT ,
KATEGORI_NO INT 
CONSTRAINT YAZAR_NO_FK FOREIGN KEY (YAZAR_NO) REFERENCES YAZARLAR ([YAZAR_NO]),
CONSTRAINT KATEGORI_NO_FK FOREIGN KEY (KATEGORI_NO) REFERENCES KATEGORI([KATEGORI_NO]),
)

CREATE TABLE EMANET_KITAPLAR(
EMANET_NO INT PRIMARY KEY,
UYE_NO INT,
KITAP_NO INT,
MIKTAR INT,
EMANET_TARIHI DATETIME,
TESLIM_TARIHI DATETIME
CONSTRAINT KITAP_NO_FK FOREIGN KEY (KITAP_NO) REFERENCES KITAPLAR ([KITAP_NO]),
CONSTRAINT UYE_NO_FK FOREIGN KEY (UYE_NO) REFERENCES UYELER([UYE_NO]),
)*/
/*RUMEYSANURASLAN*/

/*INSERT INTO UYELER (UYE_NO,UYE_AD,UYE_SOYAD,CINSIYET,TELEFON,E_POSTA) VALUES (12, 'RÜMEYSA NUR' , 'ASLAN', 'KADIN', '05458057469', 'RUMEYSANURASLAN@GMAIL.COM'),(13, 'ELIF', 'ASLAN' , 'KADIN', '05458057469', 'ELIFASLAN@GMAIL.COM')
INSERT INTO ADRESLER(ADRES_NO,SEHIR,MAHALLE,CADDE,BINA_NO,POSTA_KODU,ULKE) VALUES (1,'KAYSERI', 'MEVLANA', 'IKBAL', 16, 38280, 'TÜRKIYE'),(2 ,'KAYSERI' , 'PAPATYA' , 'BADEMLI' , 17 , 38280, 'TÜRKIYE')
INSERT INTO KUTUPHANE(KUTUPHAHE_NO,ADRES_NO,TELEFON_NO,E_POSTA) VALUES (1, 1 , 55555555, 'MEVLANAKUTUPHANESI@GMAIL.COM'), (2,2,666666666 , 'BADEMLIKUTUPHANESI@GMAIL.COM')
INSERT INTO KATEGORI(KATEGORI_NO,KATEGORI_AD) VALUES (1, 'AKSIYON'),(2, 'MACERA'),(3,'KOMEDI'),(4,'KURGU')
INSERT INTO YAZARLAR(YAZAR_NO,YAZAR_ADI,YAZAR_SOYADI) VALUES (1 , 'JACK', 'LONDON'),(2,'PEYAMI' , 'SAFA' )
INSERT INTO KITAPLAR(KITAP_NO,KITAP_ADI,ISBN,SAYFA_SAYISI,YAZAR_NO,KATEGORI_NO) VALUES (1,'VAHÞETIN ÇAÐRISI', '9789944887632', 107, 1,2),(2,'FATIH HARBIYE',' 9786254085079',128,2,4)
INSERT INTO EMANET_KITAPLAR(EMANET_NO,UYE_NO,KITAP_NO,MIKTAR,EMANET_TARIHI,TESLIM_TARIHI) VALUES (1, 12, 1, 1, 20/03/2024, 23/03/2024),(2,13,1,2,17/02/2024, 06/03/2024)*/



/*SELECT DISTINCT * FROM UYELER
SELECT DISTINCT * FROM ADRESLER
SELECT DISTINCT * FROM KUTUPHANE
SELECT DISTINCT * FROM KATEGORI
SELECT DISTINCT * FROM YAZARLAR
SELECT DISTINCT * FROM KITAPLAR
SELECT DISTINCT * FROM EMANET_KITAPLAR */

